
language: go
go:
 - 1.3
 - 1.4
 - 1.5
 - 1.6
 - tip

before_install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert

script:
  - go build
  - go test -tags integration ./...
  - go vet
  - cd sample; go build


