
language: go
go:
 - 1.3
 - 1.4


before_install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert

script:
  - go build
  - go test -tags integration ./...
  - go vet
  - cd sample; go build


